name: build-bindings

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install -y libgcrypt-dev gcc-10 g++-10

    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: python setup.py build bdist
      env:
        CC: /usr/bin/gcc-10
        CXX: /usr/bin/g++-10
